### ISSUE TITLE
AssertionError: choose a window size 400 that is [2, 1]

### ISSUE THREAD

**Issue by JosenJin** [AIFSH/SenseVoice-ComfyUI#6]
Traceback (most recent call last):
  File "D:\ai\josencomfyui\ComfyUI\execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\josencomfyui\ComfyUI\execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\josencomfyui\ComfyUI\execution.py", line 165, in map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ai\josencomfyui\ComfyUI\execution.py", line 154, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\josencomfyui\ComfyUI\custom_nodes\SenseVoice-ComfyUI\__init__.py", line 49, in generate
    res = self.model.generate(
          ^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\funasr\auto\auto_model.py", line 302, in generate
    return self.inference_with_vad(input, input_len=input_len, **cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\funasr\auto\auto_model.py", line 375, in inference_with_vad
    res = self.inference(
          ^^^^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\funasr\auto\auto_model.py", line 341, in inference
    res = model.inference(**batch, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\funasr\models\fsmn_vad_streaming\model.py", line 700, in inference
    speech, speech_lengths = extract_fbank(
                             ^^^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\funasr\utils\load_utils.py", line 173, in extract_fbank
    data, data_len = frontend(data, data_len, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\funasr\frontends\wav_frontend.py", line 420, in forward
    waveforms, feats, feats_lengths = self.forward_fbank(
                                      ^^^^^^^^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\funasr\frontends\wav_frontend.py", line 355, in forward_fbank
    mat = kaldi.fbank(
          ^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\torchaudio\compliance\kaldi.py", line 591, in fbank
    waveform, window_shift, window_size, padded_window_size = _get_waveform_and_window_properties(
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\torchaudio\compliance\kaldi.py", line 142, in _get_waveform_and_window_properties
    assert 2 <= window_size <= len(waveform), "choose a window size {} that is [2, {}]".format(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: choose a window size 400 that is [2, 1]

**Comment by wanghkkk** [comment]
the same error.how can I fix this?

**Comment by lord-lethris** [comment]
Same error is there any fix
